#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

class GameOfLifeScene;
class GameOfLifePatternModel;

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private slots:
    // Generated by QtCreator
    void on_actionStart_triggered();
    void on_actionZoom_Fit_triggered();
    void on_actionZoom_Original_triggered();
    void on_actionZoom_Out_triggered();
    void on_actionZoom_In_triggered();

    void on_actionLoad_triggered();

    void on_actionStop_triggered();

private:
    Ui::MainWindow *ui;
    GameOfLifeScene * scene;
    GameOfLifePatternModel * model;
};

#endif // MAINWINDOW_H
